import type { CharacterKey } from './characters';

export type CardSpec = {
  name: string;
  type: 'Attack' | 'Skill' | 'Alteration' | 'Affliction' | string;
  cost: number;
  effect?: string[];
  text: string;
  params?: Record<string, number | string | boolean>;
  keywords?: string[]; // e.g., ['Retain']
  rarity?: 'Common' | 'Uncommon' | 'Rare';
  owners?: CharacterKey[];
  pools?: Array<'Neutral' | 'Starter' | 'Reward'>;
  tags?: string[];
  maxCopies?: number;        // default Infinity if omitted
  starterCopies?: number;    // default 1 when chosen for starters
  cid?: number;
};

export const CARD_SPECS = {
  // Keep your existing definitions; just add the new fields.
  // Examples for clarity—adjust to your actual rules text/numbers:
  Strike: {
    name: 'Strike',
    type: 'Attack',
    params: { damage: 6 },
    cost: 1,
    text: 'Deal {damage} damage.',
    rarity: 'Common',
    owners: [],                 // Neutral
    pools: ['Neutral', 'Starter'],
    maxCopies: 10,
  },
  Guard: {
    name: 'Guard',
    type: 'Skill',
    params: { block: 5 },
    cost: 1,
    text: 'Gain {block} block.',
    rarity: 'Common',
    owners: [],                 // Neutral
    pools: ['Neutral', 'Starter'],
    maxCopies: 10,
  },
  // Ren Cards
  IronSummoningSpear: {
    name: 'Iron Summoning: Spear',
    type: 'Attack',
    params: { damage: 7 },
    keywords: ['Retain'],
    cost: 1,
    text: 'Deal {damage} damage. Retain.',
    rarity: 'Common',
    owners: ['Ren'],
    pools: ['Reward', 'Starter'],
    tags: ['IronSummoning', 'Spear'],
    maxCopies: 10,
    starterCopies: 1,
  },
  IronSummoningCauldron: {
    name: 'Iron Summoning: Cauldron',
    type: 'Skill',
    params: { block: 6, CardId: 'AwenEmpower', count: 1 },
    cost: 1,
    effect: ['addCardToHand'],
    text: 'Gain {block} Block. Add {count} {cardName} to your hand.',
    rarity: 'Common',
    owners: ['Ren'],
    pools: ['Reward', 'Starter'],
    tags: ['IronSummoning', 'Cauldron'],
    maxCopies: 10,
    starterCopies: 1,
  },
  IronSummoningRain: {
    name: 'Iron Summoning: Rain',
    type: 'Attack',
    params: { tag: 'IronSummoning', damagePer: 3, aoe: true },
    cost: 1,
    effect: ['hitsPerTag'],
    text: 'For each {tagLabel} card in your hand, deal {damagePer} damage to {targets}.',
    rarity: 'Common',
    owners: ['Ren'],
    pools: ['Reward', 'Starter'],
    tags: ['IronSummoning'],
    maxCopies: 10,
    starterCopies: 1,
  },
  AwenEmpower: {
    name: 'Awen: Empower',
    type: 'Skill',
    params: { amount: 1 },
    keywords: ['Exhaust'],
    cost: 1,
    effect: ['gainEmpower'],
    text: 'Gain {amount} Empower.',
    rarity: 'Common',
    owners: ['Ren'],
    pools: ['Reward', 'Starter'],
    tags: ['Awen'],
    maxCopies: 10,
    starterCopies: 2,
  },
  AwenManifold: {
    name: 'Awen: Manifold',
    type: 'Skill',
    params: { factor: 2, tag: 'IronSummoning', requires: { tag: 'Awen', amount: 2, consume: 'all' } },
    keywords: ['Exhaust'],
    cost: 1,
    effect: ['multi'],
    text: 'If you have {requires.amount} or more {requires.tagLabel} cards in your hand, discard them all. {factorLabel} the effect of your next {tagLabel} card.',
    rarity: 'Uncommon',
    owners: ['Ren'],
    pools: ['Reward', 'Starter'],
    tags: ['Awen'],
    maxCopies: 10,
  },
  AwenAcumen: {
    name: 'Awen: Acumen',
    type: 'Skill',
    params: { energy: 1 },
    keywords: ['Exhaust'],
    cost: 0,
    effect: ['gainEnergy'],
    text: 'Gain {energy} Energy. Exhaust.',
    rarity: 'Uncommon',
    owners: ['Ren'],
    pools: ['Reward', 'Starter'],
    tags: ['Awen'],
    maxCopies: 10,
  },
  // Winnifred/Calaera Cards
  Slash: {
    name: 'Slash',
    type: 'Attack',
    params: { damage: 6 },
    cost: 1,
    effect: ['changeAsh'],
    text: 'Deal {damage} damage. Enter Ash form.',
    rarity: 'Common',
    owners: ['Winnifred', 'Calaera'],
    pools: ['Reward', 'Starter'],
    tags: ['Ash'],
    maxCopies: 10,
    starterCopies: 1,
  },
  Burst: {
    name: 'Burst',
    type: 'Attack',
    params: { damage: 8, ifEmber: { burning: 1 } },
    cost: 1,
    effect: ['changeEmber'],
    text: 'Deal {damage} damage. Enter Ember form. If already in Ember form, apply {ifEmber.burningText}.',
    rarity: 'Common',
    owners: ['Winnifred', 'Calaera'],
    pools: ['Reward', 'Starter'],
    tags: ['Ember'],
    maxCopies: 10,
    starterCopies: 1,
  },
  Detonation: {
    name: 'Detonation',
    type: 'Attack',
    params: { damage: 6, aoe: true, ifEmber: { aoe: true, burning: 3 } },
    cost: 2,
    text: 'Deal {damage} damage to {targets}. If in Ember form, also apply {ifEmber.burningText} to {ifEmber.targets}.',
    rarity: 'Common',
    owners: ['Winnifred', 'Calaera'],
    pools: ['Reward', 'Starter'],
    tags: ['Ember'],
    maxCopies: 10,
    starterCopies: 1,
  },
  Dissociation: {
    name: 'Dissociation',
    type: 'Skill',
    cost: 1,
    effect: ['dissociation'],
    text: 'Switch forms: If you are Ash, become Ember. If you are Ember, become Ash.',
    rarity: 'Uncommon',
    owners: ['Winnifred', 'Calaera'],
    pools: ['Reward', 'Starter'],
    tags: [],
    maxCopies: 10,
  },
  AshenScale: {
    name: 'Ashen Scale',
    type: 'Skill',
    params: { duration: 3, reduceIncoming: 3 },
    cost: 2,
    effect: ['ashScales', 'changeAsh'],
    text: 'Gain {duration} Scale(s). Each Scale reduces incoming damage by {reduceIncoming}. Enter Ash form.',
    rarity: 'Uncommon',
    owners: ['Winnifred', 'Calaera'],
    pools: ['Reward'],
    tags: ['Ash'],
    maxCopies: 10,
  },
  Eviscerate: {
    name: 'Eviscerate',
    type: 'Attack',
    params: { hits: 3, damage: 7, extraHit: { condition: { form: 'Ash' }, hits: 1, damage: 7 } },
    cost: 2,
    effect: ['extraHit'],
    text: 'Deal {damage} damage {hits} time(s). If in {extraHit.condition.form} form, deal {extraHit.damage} damage {extraHit.moreTimesText}.',
    rarity: 'Uncommon',
    owners: ['Winnifred', 'Calaera'],
    pools: ['Reward', 'Starter'],
    tags: ['Ash'],
    maxCopies: 10,
  },
  // Tatsuya Cards
  VorpalSlash: {
    name: 'Vorpal Slash',
    type: 'Attack',
    params: { damage: 7, cost: { hp: 2 }, amount: 1 },
    cost: 1,
    effect: ['selfDamage', 'gainEmpower'],
    text: 'Deal {damage} damage, lose {cost.hp} HP. Gain {amount} Empower.',
    rarity: 'Common',
    owners: ['Tatsuya'],
    pools: ['Reward', 'Starter'],
    tags: ['Vorpal'],
    maxCopies: 10,
    starterCopies: 1,
  },
  Bandersnatch: {
    name: 'Bandersnatch',
    type: 'Skill',
    params: { cantAct: 1, target: 'enemy' },
    cost: 1,
    effect: ['cantAct'],
    text: 'Enemy Can\'t Act for {cantAct} turn(s).',
    rarity: 'Common',
    owners: ['Tatsuya'],
    pools: ['Reward', 'Starter'],
    tags: ['Status'],
    maxCopies: 10,
    starterCopies: 1,
  },
  VorpalClaw: {
    name: 'Vorpal Claw',
    type: 'Attack',
    params: { source: 'damageTakenThisTurn', aoe: true },
    keywords: ['End Turn'],
    cost: 1,
    effect: ['difference'],
    text: 'Deal damage to {targets} based on damage done to you ({source.damageTakenThisTurn}). End turn.',
    rarity: 'Common',
    owners: ['Tatsuya'],
    pools: ['Reward'],
    tags: ['Vorpal'],
    maxCopies: 10,
    starterCopies: 1,
  },
  Diebandersnatch: {
    name: 'Diebandersnatch',
    type: 'Attack',
    params: { damage: 30, cost: { hp: 5 }, requires: { status: 'cantAct', consume: true } },
    cost: 1,
    effect: ['requireStatus', 'selfDamage'],
    text: 'Can only be used against an enemy that {requires.statusLabel}. Deal {damage} damage and Lose {cost.hp} HP.',
    rarity: 'Uncommon',
    owners: ['Tatsuya'],
    pools: ['Reward', 'Starter'],
    tags: ['Ember'],
    maxCopies: 10,
    starterCopies: 1,
  },
  Jabberwock: {
    name: 'Jabberwock',
    type: 'Alteration',
    params: { CardId: 'VorpalSlash', count: 1 },
    keywords: ['Exhaust'],
    cost: 2,
    effect: ['addEachTurn'],
    text: 'At the start of each turn, add {count} {cardName} to your hand. Exhaust.',
    rarity: 'Uncommon',
    owners: ['Tatsuya'],
    pools: ['Reward'],
    tags: ['Vorpal'],
    maxCopies: 10,
    starterCopies: 1,
  },
  Intimidation: {
    name: 'Intimidation',
    type: 'Skill',
    params: { weak: 1, exposed: 1, aoe: true },
    keywords: ['Exhaust'],
    cost: 0,
    effect: ['weak', 'exposed'],
    text: 'Apply {weakText} and {exposedText} to {targets}. Exhaust.',
    rarity: 'Uncommon',
    owners: ['Tatsuya'],
    pools: ['Reward', 'Starter'],
    tags: ['Status'],
    maxCopies: 10,
  },

  // ===== Enemy cards (content-only right now) =====
  EnemyStrike: {
    name: 'Enemy Strike',
    type: 'Attack',
    cost: 0,
    params: { damage: 6 },
    effect: [], // resolved by AI path, not player pipeline
    tags: ['Enemy'],
    owners: ['Enemy'],
    text: 'Deal 6 damage.',
  },
  EnemyExpose: {
    name: 'Expose',
    type: 'Skill',
    cost: 0,
    params: { target: 'enemy', exposed: 1 },
    effect: ['exposed'],
    tags: ['Enemy', 'Debuff'],
    owners: ['Enemy'],
    text: 'Apply 1 Exposed.',
  },
  EnemyBlock: {
    name: 'Guard',
    type: 'Skill',
    cost: 0,
    params: { block: 6 },
    effect: ['gainBlock'],
    tags: ['Enemy', 'Defense'],
    owners: ['Enemy'],
    text: 'Gain 6 Block.',
  },
  EnemyZap: {
    name: 'Zap',
    type: 'Attack',
    cost: 0,
    params: { target: 'enemy', damage: 6, weak: 2 },
    effect: ['weak'],
    tags: ['Enemy', 'Magic'],
    owners: ['Enemy'],
    text: 'Deal 5 damage and apply 2 Weak.',
  },
  EnemyEmpower: {
    name: 'Empower',
    type: 'Skill',
    cost: 0,
    params: { amount: 1, target: 'self' },
    effect: ['empower'],
    tags: ['Enemy', 'Buff'],
    owners: ['Enemy'],
    text: 'Gain 1 Empower.',
  },
  EnemyBurn: {
    name: 'Scorch',
    type: 'Skill',
    cost: 0,
    params: { burning: 2, target: 'enemy' },
    effect: ['burning'], 
    tags: ['Enemy', 'Magic'],
    owners: ['Enemy'],
    text: 'Apply 2 Burning.',
  },
  EnemyAllyEmpower: {
    name: 'Rally',
    type: 'Skill',
    cost: 0,
    params: { amount: 1, target: 'ally' },
    effect: ['empower'],
    tags: ['Enemy', 'Support'],
    owners: ['Enemy'],
    text: 'Give an ally +1 Empower.',
  },
  EnemyMinorHeal: {
    name: 'Mend',
    type: 'Skill',
    cost: 0,
    params: { heal: 6, target: 'ally' },
    effect: [], // handled by AI → heal intent path
    tags: ['Enemy', 'Support'],
    owners: ['Enemy'],
    text: 'Heal an ally for 6.',
  },
  EnemyAllyBlock: {
    name: 'Guard Ally',
    type: 'Skill',
    cost: 0,
    params: { block: 6, target: 'ally' },
    effect: [], // handled by AI → buff Block path
    tags: ['Enemy', 'Support', 'Defense'],
    owners: ['Enemy'],
    text: 'Give an ally 6 Block.',
  }
} as const satisfies Record<string, CardSpec>;

export type CardId = keyof typeof CARD_SPECS;
